---
- name: Configuration SSH et installation de Docker
  hosts: all
  become: yes
  vars:
    ssh_port: 1373
    sshd_config_path: /etc/ssh/sshd_config
    sshd_config_d_path: /etc/ssh/sshd_config.d/
    local_key_path_id_rsa: "C:/Téléchargements/id_rsa.pub"
    local_key_path_eseo: "C:/Téléchargements/eseo.pub"

  tasks:
    - name: Copier la clé de Julien sur les serveurs cibles
      ansible.builtin.copy:
        src: "{{ local_key_path_id_rsa }}"
        dest: /root/.ssh/authorized_keys
        owner: root
        mode: 0600

    - name: Copier la clé de Matthieu sur les serveurs cibles
      ansible.builtin.copy:
        src: "{{ local_key_path_eseo }}"
        dest: /root/.ssh/authorized_keys
        owner: root
        mode: 0600

    - name: Désactiver la connexion par mot de passe dans sshd_config
      ansible.builtin.lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes

    - name: Désactiver la connexion par mot de passe dans tous les fichiers *.conf de sshd_config.d
      ansible.builtin.find:
        paths: "{{ sshd_config_d_path }}"
        patterns: '*.conf'
      register: conf_files

    - name: Appliquer PasswordAuthentication no dans chaque fichier .conf
      ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes
      loop: "{{ conf_files.files }}"

    - name: Modifier le port SSH
      ansible.builtin.lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^#?Port'
        line: "Port {{ ssh_port }}"
        state: present
        backup: yes

    - name: Désactiver le port 22 (ancien port SSH)
      ansible.builtin.lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^#?Port 22'
        state: absent
        backup: yes

    - name: Activer UFW
      ansible.builtin.command:
        cmd: ufw enable
      ignore_errors: yes

    - name: Autoriser le port 1373 pour SSH
      ansible.builtin.ufw:
        rule: allow
        port: "{{ ssh_port }}"
        proto: tcp

    - name: Supprimer l'autorisation du port 22
      ansible.builtin.ufw:
        rule: delete
        port: 22
        proto: tcp

    - name: Redémarrer le service SSH pour appliquer les modifications
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Installer Docker
      ansible.builtin.package:
        name: docker
        state: present
